# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: Run tests
    deps:
      - unit

  unit:
    desc: Run unit tests
    cmd: ginkgo run --label-filter=!conformance --race --cover ./...

  cover:
    desc: Run coverage report
    cmd: go tool cover -html=coverprofile.out

  conformance:
    desc: Run conformance tests
    cmd: ginkgo run --label-filter=conformance ./...

  management:
    desc: Run manage API tests
    cmd: ginkgo run --label-filter=management ./...
