# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: Run tests
    deps:
      - unit

  unit:
    desc: Run unit tests
    cmd: ginkgo run --label-filter=!conformance --race --cover ./{internal,pkg,cmd}/...

  cover:
    desc: Run coverage report
    cmd: go tool cover -html=coverprofile.out

  integration:
    desc: Run integration tests
    deps:
      - conformance
      - management

  conformance:
    desc: Run conformance tests
    cmd: ginkgo run --label-filter=conformance ./integration/conformance

  management:
    desc: Run manage API tests
    cmd: ginkgo run --label-filter=management ./integration/management

  authorization:
    desc: Run authorization tests
    cmd: ginkgo run --label-filter=authorization ./integration/conformance
