name: Test, lint, build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ~/.asdf
          key: |
            asdf-${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            asdf-${{ runner.os }}-

      - uses: asdf-vm/actions/install@v4

      - name: Run linter
        run: task lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ~/.asdf
          key: |
            asdf-${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            asdf-${{ runner.os }}-

      - uses: asdf-vm/actions/install@v4


      - name: Run tests
        run: task test test:integration

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ~/.asdf
          key: |
            asdf-${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            asdf-${{ runner.os }}-

      - uses: asdf-vm/actions/install@v4

      - uses: ko-build/setup-ko@v0.9

      - name: Build and push image with ko
        env:
          KO_DOCKER_REPO: ghcr.io/zhulik
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ko build -B --tags latest github.com/zhulik/d3/cmd/server
